\lefthyphenmin=62
\righthyphenmin=62
# Tilastotieteen kehityksen nykytrendejä {#luku14}

## Modernin tilastotieteen suuntaviivoja

Seuraavassa vielä joitain tilastotiedettä parhaillaan koskevia kehitystrendejä, joita olemme myös osaltaan sivunneet tämän kurssimateriaalin myötä:

- __Aineistot kasvavat ja monimutkaistuvat__. Näin ollen tilastotietedettä ja tilastollisten menetelmien kehitystyötä tullaan tarvitsemaan (yhä suuremmin) jatkossakin.

- Informaatiota on tarjolla (paljon) enemmän kuin osaamme sitä hyödyntää. __Informaatio ei ole enää niukka hyödyke__. Keskeistä on kuitenkin, että (useimmiten) suhteellisen pieni osa informaatiosta on hyödyllistä.
  - Havaitsemme informaatiota (osin) ja valikoivasti subjektiivisesti. Luulemme haluavamme lisää informaatiota, kun todellisuudessa haluamme tietoa (ts. signaaleja kun vastaavasti kasvava määrä kohinaa yrittää vaikeuttaa tätä signaalin erottamista kohinasta).
- __Laskennallisuus__ kasvaa. Tietokoneiden laskentakapasiteetti nousee vaikkakin suhteellinen kasvu ei ehkä olekaan enää niin suurta mitä muutamat viime vuosikymmenet.
- Osin laskennallisuuteen liittyvä __koneoppimisen__ kehittyminen ja sen "rajatieteiden" yhteyteen integroituneet käytännöt ja menetelmäkehitystyö tulee jatkumaan. 
  - Toisaalta "perinteiselle" tilastotieteelle on edelleen myöskin vahva oma roolinsa monilla eri tieteenaloilla.
- __Analyysien automatisointi__: Tilastolliset ohjelmat alkanevat jatkossa tulkita tuloksia osin automaattisesti. Mihin tarvitaan tilastotieteilijää? Kokonaisvaltaiseen tutkimusprosessin valvontaan(?)
  - Osin edelliseen liittyen jo nyt ja jatkossa luultavasti yhä enemmän korostuu se, että melkein kuka vaan voi tehdä tilastollisia analyysejä. Niin valmiita paketteja jne. on jo saatavilla. "Tilastotieteellinen faktantsekkaus" noussee vahvemmin esille eli tilastollisten menetelmien käyttäjän on sittenkin edelleen kyettävät arvioimaan ovatko tulokset uskottavia ja vapaita ilmeisistä hankaluuksista.
  - Näiltä osin yksi keskeinen kehityssuunta on jo vahvasti yleistyneet laajat tekoälymallit kuten OpenAI:n toteuttama [ChatGPT](https://chat.openai.com/).
    - ChatGPT:tä käytetäänkin jo laajalti mm. tilastollisen ohjelmoinnin apuvälineenä. Nopeasta kehityksestä huolimatta ChatGPT:n antamat vastaukset ovat kuitenkin paikoin epäluotettavia tai suorastaan väärin, joten sen käytössä korostaa edelleen vahvan tilastotieteellisen osaamisen lisäksi substanssiosaaminen.
- __Poikkitieteellisyys__ tulee entisestäänkin vahvistumaan. Ts. substanttitietouden ja tilastotieteen yhdistäminen ja sen tärkeys ei tule ainakaan vähenemään. Sivuaineopintoja kannattaa siis käydä ja ottaa opinto-ohjelmaan.
  - Tämän lisäksi kokonaisvaltaisesti tilastotieteen ytimen osaajien osaamista tulla kysymään jatkossakin.

\

- Oheisten huomioiden ohella lopuksi on syytä korostaa tilastotieteen opiskelun näkökulmasta, että oikotietä ei ole! __Oikaista siis ei voi__: Ensin on rakennettava vahva tilastollisen ajattelun ja menetelmien perusta (__alkaen todennäköisyyslaskennasta ja tilastollisesta päättelystä__), jotta myöhemmin voi kehittyä ja omata todellisia kykyjä ottaa vastaan monia jo varsin monimutkaisia tilastollisia menetelmiä!

## Luvun 14 yhteenveto, keskeisiä termejä ja kokonaisuuksia.

- Aineistot kasvavat ja monimutkaistuvat
- Informaatio ei ole enää niukkaa
- Laskennallisuus kasvaa
- Koneoppimisen vahvistuminen ja kehittyminen
- Analyysien automatisoituminen
- Poikkitieteellisyys