--- 
title: "TILM3701 - Tilastotiede ja data 2024"
author:
  - Koonneet
  - Henri Nyberg^[Turun yliopisto, matematiikan ja tilastotieteen laitos, henri.nyberg@utu.fi]
  - Roope Rihtamo^[Turun yliopisto, matematiikan ja tilastotieteen laitos, roope.rihtamo@utu.fi]
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
urlcolor: blue
linkcolor: blue
github-repo: rstudio/bookdown-demo
description: "Tilastotieteen ensimmäinen kurssi."
header-includes: |
    \def\independenT#1#2{\mathrel{\rlap{$#1#2$}\mkern2mu{#1#2}}}
    \newcommand{\indep}{\perp \!\!\! \perp}
---

# Kurssin (osat I ja II rakenne) {-}
- Tilastotiede ja data -kurssi koostuu kahdesta erillisestä osasta, jotka tarjoavat opiskelijalle työkaluja tieteen ja tutkimuksen ymmärtämiseen tilastotieteen näkökulmasta käsin.
- __Osa I__: Ensimmäinen osa toimii johdantokurssina tieteen ja tutkimuksen tekoon esittelemällä keskeisiä käsitteitä, käytäntöjä ja termejä, joita kvantitatiivisessa/määrällisessä tutkimuksessa tilastotieteen ja sen menetelmien osalta tarvitaan (ks. osaamistavoitteet alla).
  - Tarkoituksena on yleisellä tasolla johdatella tilastotieteen ja aineistojen (datan) maailmaan sekä pohtia myös näiden laajempaa merkitystä tieteellisen tutkimuksen hyvin keskeisinä osina.
  - Osa I koostuu X luennosta ja ... 
  - Kurssin ensimmäisen osan lopuksi järjestetään tentti, joka arvioidaan hyväksytty/hylätty asteikolla.
  
- __Osa II__: Kurssin toisessa osassa syvennytään ensimmäisen osan teemoihin tarkastelemalla erityisesti tilastollisten menetelmien roolia tutkimuksessa.
  - Tarkoituksena on luoda pohja tosielämän satunnaisilmiöiden tutkimukselle tilastotieteen ja tilastollisten menetelmien keinoin.
  - Osa II koostuu 7 luennosta, tutoriaalitilaisuuksista sekä harjoitustehtävistä.
  - Harjoitustehtävien tavoite on totuttaa opiskelija erityisesti matematiikan ja tilastotieteen opinnoissa yleiseen viikottaisten harjoitustehtävien tekemisen käytäntöön.
  - Kurssin toisen osan lopuksi järjestetään tentti, joka arvioidaan 0-5 arviointiasteikolla.

- Kurssilla vältetään kovin teknistä matemaattista esitystapaa, mutta erityisesti osassa II, tarvittavissa määrin, tullaan kuitenkin käyttämään tilastotieteen perusopinnoissa käytettäviä matemaattisia merkintöjä ja määritelmiä. 
  - Esim. todennäköisyyslaskennan ja tilastollisen päättelyn perusteita ei käydä vielä riittävällä matemaattisella tarkkuudella lävitse, vaan nämä tarkastelut jäävät tätä kurssia seuraavien kurssien ([TILM3553 Todennäköisyyslaskennan    peruskurssi](https://opas.peppi.utu.fi/fi/opintojakso/TILM3553/1734?period=2022-2024) tai [TILM3568 Todennäköisyyslaskenta   sivuaineopiskelijoille](https://opas.peppi.utu.fi/fi/opintojakso/TILM3568/3385?period=2 022-2024) sekä [TILM3555 Tilastollisen päättelyn  peruskurssi](https://opas.peppi.utu.fi/fi/opintojakso/TILM3555/1731?period=2022-2024))  asiaksi. Nämä kurssit, yhdessä alkuvaiheen pakollisten matematiikan kurssin lisäksi, muodostavat siis tämän kurssin kanssa lähtökohdan tilastotieteen opinnoille (Turun yliopistossa).

# Kurssimateriaali {-}

- Luennot eivät suoraan perustu yhteen kirjaan tai lähteeseen. Käytettyjä lähdemateriaaleja luetellaan alapuolella oheislukemiston myötä. 

- Oheislukemistoa (sopivilta osin):
  - Mellin, I. (2004). Johdatus tilastotieteeseen: Tilastotieteen johdantokurssi (1.kirja). Yliopistopaino, Helsingin yliopisto.
  - Mellin, I. (2000). Johdatus tilastotieteeseen: Tilastotieteen jatkokurssi (2.kirja). Yliopistopaino, Helsingin yliopisto.
  - Mellin, I. (2006). Tilastolliset menetelmät. Luentomoniste, Aalto yliopisto (TKK).
  - Holopainen, M. ja P. Pulkkinen (2008). Tilastolliset menetelmät. Sanoma Pro Oy.
  - Pahkinen, E. ja R. Lehtonen (1989). Otanta-asetelmat ja tilastollinen analyysi. Gaudeamus, Helsinki.
  - Pahkinen, E. ja R. Lehtonen (2004). Practical Methods for Design and Analysis of Complex Surveys. 2. painos, Wiley.
  - Sund, R. (2003). Tilastotiede käytännön tutkimuksessa -kurssi. Helsingin yliopisto.
  - Silver, N. (2014). Signaali ja kohina: Miksi monet ennusteet epäonnistuvat mutta jotkin eivät? Terra Cognita. (Suomentanut Kimmo Pietiläinen)
    - Englanninkielinen teos: Silver, N. (2015). The Signal and the Noise: Why So Many Predictions Fail--but Some Don't. Penguin Books; Illustrated edition
  - Pesonen, M. (2017). Kurssimateriaali kurssille Aineistonhankinta ja tutkimusasetelmat, Turun yliopisto.
  - Vartia, Y. (1989). Tilastotieteen perusteet. Yliopistopaino, Helsinki. II painos.

- Muita taustamateriaaleja
    - [Tilastokeskuksen tilastokoulu (linkki)](https://tilastokoulu.stat.fi/verkkokoulu_v2.xql?course_id=tkoulu_tilaj&lesson_id=1&subject_id=0&page_type=sisalto)
    - Tilastotieteen sanasto suomi-englanti-suomi, ks. Juha Alho, Elja Arjas, Esa Läärä ja Pekka Pere (2021). [Tilastotieteen sanasto. Suomen Tilastoseuran julkaisuja 8.](https://tilastoseura.fi/)

- Suuret kiitokset Visa Kuntzelle ja Emil Lehdelle kommenteista ja avusta materiaalin työstämisessä. Kaikki jäljelle jääneet painovirheet ovat materiaalin kokoajien.

# Osaamistavoitteet {-}

- Kurssin materiaali on koostettu em. lähteistä ja pyrkii paikoin pelkistettyyn esitysmuotoon mutta kuitenkin niin että materiaalin opiskelemalla kurssien osaamistavoitteet täyttyvät kokonaisuudessaan. 
- Osaamistavoitteet on listattu Turun yliopiston opinto-oppaassa matematiikan ja tilastotieteen laitoksen opintotarjonnasta kurssikuvauksien alta ([Osa 1](https://opas.peppi.utu.fi/fi/opintojakso/TILM3712/102471?period=2024-2027) ja [Osa 2](https://opas.peppi.utu.fi/fi/opintojakso/TILM3713/102472?period=2024-2027)) ja ne löytyvät alta vielä laajemmin. 

- __Osa I__: Opintojakson suoritettuaan opiskelija
  - on saanut kokonaiskuvan tilastotieteestä ja sen perusteista  
  - on sisäistänyt tilastotieteen keskeisiä käsitteitä ja osaa niiden avulla tarkastella     kriittisesti tieteellisiä tutkimuksia  
  - pystyy erottamaan edustavan otoksen ja näytteen  
  - tuntee tilastotieteen keskeiset perustunnusluvut   

  

- __Osa II__: Opintojakson suoritettuaan opiskelija on täydentänyt osassa I opittuja tilastotieteen perustietoja mm. seuraavilta osin:
  - osaa hahmottaa tilastotieteen roolin omana tieteenalana ja eri sovellusalueiden           yhteydessä
  - tunnistaa erilaiset tutkimusasetelmat ja aineistotyypit
  - ymmärtää otannan ja otantateorian perusteet
  - hahmottaa tilastollisen riippuvuuden, korrelaation ja yksinkertaisen lineaarisen          regressiomallin idean
  - ymmärtää tilastollisen ennustaminen perusajatukset

# Kurssin sisältö {-}
Kurssin osien II ja II sisältöjä on listattu opinto-oppaassa ja laajemmin alla. Tämä listaus toimii hyvänä luettelona kurssin keskeisistä teemoista.

- __Osa I__
  - Tieteellinen tieto, tilastot ja arkitieto yhteiskunnassa
  - Tilastotiede tieteenalana ja sen suhde lähitieteisiin, kuten datatieteeseen (data science)
  - Sattuma ja satunnaisuus tilastotieteessä
  - Tilastolliset aineistot (data), niiden kerääminen ja mittaaminen
  - Tilastollinen riippuvuus ja korrelaatio

- __Osa 2__
  - Tilastolliset mallit ja jakaumat
  - Otantamenetelmien perusteet
  - Tilastollisen päättelyn perusteita
  - Regressioanalyysin perusteet
  - Tilastotieteen rooli uuden tieteellisen tiedon tuottamisessa
  - Aineisto- ja tutkimustyypit ja koeasetelmat tilastotieteessä
  - Tilastotieteen sovellusten ja sovellusalueiden esittelyä

Materiaalin seassa on eritelty väärikoodatuin tietolaatikoin erinäisiä tärkeitä tilastotieteellisiä konsepteja ja termejä sekä esimerkkejä tilastotieteen sovelluksista. Näistä ensin mainitut löytyvät Deltan violeteista laatikoista ja jälkimmäiset Statistikan oransseista.^[Toim. Huom. värit eivät täysin alkuperäisten värien kanssa yhteneväisiä.] Alla esimerkkilaatikot.

::: {.defblock data-latex="{}"}
**Konsepti tai termi**

Konseptin tai termin löyhä määritelmä.
:::

::: {.eblock data-latex="{}"}
**Esimerkki**

Aihetta koskeva esimerkki.
:::
